name: Environment Provisioning

on:
  create:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_mysql_password: ${{ secrets.MYSQL_PASSWORD }}
 
    steps:
    - uses: actions/checkout@v2
    
    - name: Install aws-iam-authenticator
      run: |
        echo Installing aws-iam-authenticator...
        mkdir ~/aws
        curl -Lo ~/aws/aws-iam-authenticator \
        "https://github.com/kubernetes-sigs/\
        aws-iam-authenticator/releases/download/\
        v0.5.9/aws-iam-authenticator_0.5.9_linux_amd64"
        chmod +x ~/aws/aws-iam-authenticator
        sudo cp ~/aws/aws-iam-authenticator /usr/local/bin/aws-iam-authenticator

    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5.6

    - name: Terraform fmt
      run: terraform fmt

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate -no-color

    - name: Terraform Plan
      run: terraform plan -no-color
    
    - name: Terraform Apply
      run: terraform apply -no-color -auto-approve 

    - name: Upload kubeconfig file
      uses: actions/upload-artifact@v2
      with:
        name: kubeconfig
        path: kubeconfig
